FROM openjdk:11
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=/Users/felipegomes/Documents/workspace-spring-tool-suite-4-4.14.1.RELEASE/alura-challenger-be/target/Alura-Challenger.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]